### ISSUE TITLE
not running without --no-sandbox option

### ISSUE THREAD

**Issue by ksharindam** [ivan-hc/Chromium-Web-Browser-appimage#1]
If Chromium appimage is launched normally it does not open.
But if --no-sandbox option is passed, it opens with a warning.
how to use it with chromium-sandbox ?

**Comment by ivan-hc** [comment]
Strange, it works fine for me, i can't reproduce the problem

Try to run the AppImage from the terminal, maybe there is something missing on your host system.


https://user-images.githubusercontent.com/88724353/208446458-e4527f86-6d02-4a4c-a943-058032432015.mp4

**Comment by ksharindam** [comment]
It is showing this error...
```
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap
```

The workaround I have found is 
`sudo sysctl kernel.unprivileged_userns_clone=1`

But each time I reboot , I need to reenter the command.
So I have added the line in /etc/rc.local script

**Comment by ksharindam** [comment]
You should add this troubleshoot in README.md

**Comment by ivan-hc** [comment]
this is already explained at https://docs.appimage.org/user-guide/troubleshooting/electron-sandboxing.html

**Comment by ksharindam** [comment]
Those who downloads from your repo, might not be aware of this link.
So, add either this link, or the troubleshoot in the readme file.

**Comment by ivan-hc** [comment]
Thank you very much for this issue, see https://github.com/ivan-hc/Chromium-Web-Browser-appimage/commit/c07fe08e54df6ad238285112ea24d73cb7dd206d
