### ISSUE TITLE
Add arm64 arch

### ISSUE THREAD

**Issue by aaasoft** [ivan-hc/Chromium-Web-Browser-appimage#4]
Thanks for your awesome work.I need to run Chromium on arm64 arch.Can you add arm64 arch release file?

**Comment by ivan-hc** [comment]
I can't, I have not an ARM device that I can use to build packages. Only AMD64 and i386. Sorry.

**Comment by aaasoft** [comment]
> I can't, I have not an ARM device that I can use to build packages. Only AMD64 and i386. Sorry.

It's OK,thanks.
