### ISSUE TITLE
Can't find source path /run/user

### ISSUE THREAD

**Issue by 2011** [ivan-hc/Chromium-Web-Browser-appimage#5]
```
$ /path/to/Chromium_123.0.6312.105-1-archimage3.4-x86_64.AppImage 
bwrap: Can't find source path /run/user: No such file or directory
```

I also tried this with the -no-sandbox parameter (no difference).

Indeed /run/user/ does not exist (I suppose I could just create that directory, but somehow editing /run/ just doesn't feel right to me).

I regularly run more than 40 different AppImages (many of them Electron-based), and have never seen this error before.

My /etc/sysctl.conf file does indeed have `kernel.unprivileged_userns_clone = 1` in it, but unprivileged_userns_clone does not exist in /proc/sys/kernel/ (it must have in the past, or I wouldn't have added the line enabling it to /etc/sysctl.conf).

Any help appreciated. Thank you in advance.

**Comment by ivan-hc** [comment]
This is not a normal AppImage, but an Archimage, it is an Arch Linux container ([JuNest](https://github.com/fsquillace/junest)) into an AppImage, with only whatthe app needs to run.

The error you have come from this line of the official code:

https://github.com/fsquillace/junest/blob/4d2d0fcb840d9266a39deb0acf2afc44973bf5f3/lib/core/namespace.sh#L14

to run as a guest system/container on your host system, JuNest uses its inbuilt copy of Bubblewrap, and the line above means that /run/user is one of the mountpoints that JuNest uses to run as it should (the "$COMMON_BWRAP_OPTION" environment variable).

On what system you're using it? from the error you got seems that your system as no /run/user path

**Comment by 2011** [comment]
> On what system you're using it? from the error you got seems that your system as no /run/user path

I run Gentoo.

Yes, I have no /run/user/ directory.

**Comment by ivan-hc** [comment]
I don't know why the developer have mounted that path, maybe it a systemd related directory? I'm not sure.

However, if for you its not a problem, its enough to create that directory on the host and it will work as expected.

**Comment by 2011** [comment]
> maybe it a systemd related directory? I'm not sure.

Certainly possible, as I don't use systemd on Gentoo.

> However, if for you its not a problem, its enough to create that directory on the host and it will work as expected.

Indeed it did run. Sadly, however, the web site that did not work correctly in my other browser (chromium-based, but I have a huge number of custom settings) did not work correctly with vanilla chromium (this AppImage) with the default settings. Obviously, no concern of yours, but I can at least report to the web site developers that I did "try another browser" (the best-supported one, no less), and that their site still does not function correctly.

Thank you for your help.
