### ISSUE TITLE
Can't see netflix with appimage

### ISSUE THREAD

**Issue by cefer60** [ivan-hc/Chromium-Web-Browser-appimage#6]
I have configured chromium to be able to watch Netflix, but when I try with the ApppImage an error appears, such as :verify in setting that the option to play protected content is enabled. I have checked and yes, the option is enabled, but the message continues to appear and the video does not play.
This does not happen if I use a chromium provided by the distribution (testing on fedora and tumbleweed)
To test netflix you can follow theses steps:
1) install google chrome
2) Locate and copy the folder WidevineCdm into ~/.config/chromium
3) copy to secure location the folder:  /opt/google/chrome
4) Uninstall google chrome
5) Restore the folder (from step 3 ) to /opt/google/chrome
6) Run chromium and test

Ah!... a netflix user is required too

**Comment by ivan-hc** [comment]
I've also AppImages for Google Chrome, Vivaldi and Opera if you need:
- https://github.com/ivan-hc/Chrome-appimage
- https://github.com/ivan-hc/Vivaldi-appimage
- https://github.com/ivan-hc/Opera-appimage
they are based on the official .deb packages

**Comment by ivan-hc** [comment]
I'm doing tests using this site https://bitmovin.com/demos/drm

its a DRM problem, I've tested this on firefox, google chrome and chromium... and the latter has not DRM support.

I'll try to fix this.

**Comment by ivan-hc** [comment]
baically, this happens because this version of Chromium I've made is based on an Arch Linux container named JuNest, and sadly this lack of hardware accelleration and other advantages of the kernel compatibility.

Maybe I should switch this again to a .deb base

**Comment by ivan-hc** [comment]
try to build an AppImage based on .deb packages from Linux Mint using this script:
```
wget https://raw.githubusercontent.com/ivan-hc/Chromium-Web-Browser-appimage/main/chromium
chmod a+x ./chromium
./chromium
```
to add Google as the main search engine, do it manually (its removed by default, see https://forums.linuxmint.com/viewtopic.php?t=402039)

**Comment by ivan-hc** [comment]
I've switched to the .deb version, now it should not have issues. Feel free to re-open this issue in case you need it. I close for inactivity.
