### ISSUE TITLE
Chromium Appimage Cannot Tigger Host Application Registered as MIME Type

### ISSUE THREAD

**Issue by KevinFan9729** [ivan-hc/Chromium-Web-Browser-appimage#7]
Hello,

I am using the Chromium AppImage and have encountered an issue with handling custom URL schemes. On my host system, I have an application that is associated with a custom URL scheme via a MIME type in its desktop file. This setup works nicely when triggered from a Chromium installation directly on the host. (i.e., the host application can be launched when the custom url is invoked in the host browser)

However, when I attempt to use the same custom URL scheme from the Chromium AppImage, the custom URL does not trigger the associated application. This issue persists despite the MIME type and desktop file being correctly configured on the host.

I notice `xdg-utils` is not included in `chromium-junest` script, so right now the Chromium AppImage cannot handle MIME type. Any idea how we can address this issue?

**Comment by ivan-hc** [comment]
I'll try to include the binaries from the package "xdg-utils" to see if it works... if there is something else I must know... for example, if you provide a video about the behaviour you expect, let me see

**Comment by ivan-hc** [comment]
Just included xdg-utils https://github.com/ivan-hc/Chromium-Web-Browser-appimage/commit/4970092aa23d51ad0e426be94e5b2e44ae64ee3a try the new AppImage available

**Comment by KevinFan9729** [comment]
Thanks for the quick response.

Not exactly a video but here is a clearer description I hope:

on host, we have an application say 'my-app' that has the following desktop defination:

```
[Desktop Entry]
Name=My Application
Exec=my-app %u
Type=Application
MimeType=x-scheme-handler/myapp;
Icon=application-icon
```
and we run `update-desktop-database` so the custom url `myapp://` will launch the application `my-app`.

Say I setup a web page that has the url `myapp://`, when I click the url through a regular chromium browser I installed on my host through the host's package manager,  the installed browser will try to run the host application  `my-app` through `xdg-open`.

Now, switching to the chromium appimage, say I launch the chromium appimage browser, then click on the same `myapp://` url, the chromium appimage will not launch the application on host.  The expected behavior is that the chormium appimage will behave the same as the installed chromium browser and it should launch the host application `my-app`.

**Comment by KevinFan9729** [comment]
> Just included xdg-utils [4970092](https://github.com/ivan-hc/Chromium-Web-Browser-appimage/commit/4970092aa23d51ad0e426be94e5b2e44ae64ee3a) try the new AppImage available

Yeah I included the `xdg-utils` myself in an experiment but unfortunately it does not do the trick.
I think the problem is that junest cannot access the MIME type on host.  There is something called `xdg-desktop-portal` [](https://wiki.archlinux.org/title/XDG_Desktop_Portal) which allows a sandbox to access outside resources via dbus, but I am not too sure how it works / configure with junest.

**Comment by ivan-hc** [comment]
> Yeah I included the `xdg-utils` myself in an experiment but unfortunately it does not do the trick. I think the problem is that junest cannot access the MIME type on host. There is something called [xdg-desktop-portal](https://wiki.archlinux.org/title/XDG_Desktop_Portal) which allows a sandbox to access outside resources via dbus. `xdg-desktop-portal` should work automatically with `Flatpak`, but I am not too sure how it works / configure with junest.

OK, the issue is that the mine is not a normal AppImage, it is already an Arch Linux container bundled into an AppImage.

However, this is not the only Chormium-based Appimage I own, I've also some built normally, from .deb packages. To see if your trick works, do a test with one of these:
- https://github.com/ivan-hc/Chrome-appimage
- https://github.com/ivan-hc/Opera-appimage
- https://github.com/ivan-hc/Vivaldi-appimage

let me know. I was already considering to switch it back to the .deb version, as before.

**Comment by KevinFan9729** [comment]
> > Yeah I included the `xdg-utils` myself in an experiment but unfortunately it does not do the trick. I think the problem is that junest cannot access the MIME type on host. There is something called [xdg-desktop-portal](https://wiki.archlinux.org/title/XDG_Desktop_Portal) which allows a sandbox to access outside resources via dbus. `xdg-desktop-portal` should work automatically with `Flatpak`, but I am not too sure how it works / configure with junest.
> 
> OK, the issue is that the mine is not a normal AppImage, it is already an Arch Linux container bundled into an AppImage.
> 
> However, this is not the only Chormium-based Appimage I own, I've also some built normally, from .deb packages. To see if your trick works, do a test with one of these:
> 
> * https://github.com/ivan-hc/Chrome-appimage
> * https://github.com/ivan-hc/Opera-appimage
> * https://github.com/ivan-hc/Vivaldi-appimage
> 
> let me know. I was already considering to switch it back to the .deb version, as before.

Yeah junest based appimage is pretty neat, but this container may not be suitable for application like a browser which needs to access a lot of host configs and resources. There is also this [Simple MIME type handling test](https://entropymine.com/jason/testbed/mime/) which I think the current junest based chromium browser fails even with `xdg-utils` I will do more testing and test out some of your regular appimages to see if the problem persist.

**Comment by ivan-hc** [comment]
Two weeks ago I have already updated, tested and keept ready to be used in replacement og the JuNest-based one

https://github.com/ivan-hc/Chromium-Web-Browser-appimage/blob/main/chromium

I can easily replace it to build the AppImage using a Debian Stable base

**Comment by KevinFan9729** [comment]
> Two weeks ago I have already updated, tested and keept ready to be used in replacement og the JuNest-based one
> 
> https://github.com/ivan-hc/Chromium-Web-Browser-appimage/blob/main/chromium
> 
> I can easily replace it to build the AppImage using a Debian Stable base

Nice, will test and report back.

**Comment by ivan-hc** [comment]
Try now

**Comment by ivan-hc** [comment]
up

**Comment by KevinFan9729** [comment]
I am having trouble packaging the regular appimage (non-junst). I tried running the `chromium` bash script, and received the following: 

`+ check_dependencies dpkg dpkg-deb convert wget grep sed cut file desktop-file-validate strings
+ for executable in $@
+ which dpkg
+ for executable in $@
+ which dpkg-deb
+ for executable in $@
+ which convert
+ echo 'convert missing'
convert missing
+ exit 1
Error opening directory “./chromium/chromium.AppDir/usr/share/glib-2.0/schemas/”: No such file or directory
No ./usr/share/glib-2.0/schemas/
`

**Comment by KevinFan9729** [comment]
Looks like the pkg2appimage stage returns 1 due to `convert missing`.

**Comment by ivan-hc** [comment]
@KevinFan9729 I've already switched Chromium to Debian Stable

download it from https://github.com/ivan-hc/Chromium-Web-Browser-appimage/releases/tag/continuous

let me know

**Comment by ivan-hc** [comment]
about pkg2appimage, you need to have imagemagick installed on your host

**Comment by KevinFan9729** [comment]
Ok, I am able to build the appimage after installing ima
However, running into the following issue now:
`./Chromium_Web_Browser-125.0.6422.141-1~deb12u1-x86_64.AppImage 
/tmp/.mount_ChromiIKjfoL/usr/lib/chromium/chromium: symbol lookup error: /tmp/.mount_ChromiIKjfoL/usr/lib/x86_64-linux-gnu/libharfbuzz-subset.so.0: undefined symbol: hb_set_copy
`
my host is Ubuntu 22.04

**Comment by ivan-hc** [comment]
can you run it using `LD_DEBUG=libs ./*.AppImage` or `LD_DEBUG=files ./*.AppImage`?

we may have more details on what is missing into the AppImage... or maybe on the host.

**Comment by KevinFan9729** [comment]
hmmm.. the output is quite large, are there any keywords we can pipe and `grep` so we can filter out the output?

**Comment by KevinFan9729** [comment]
It seems that `libharfbuzz-subset.so.0` is not in `/chromium.AppDir/usr/lib/x86_64-linux-gnu`

**Comment by ivan-hc** [comment]
references about "no such file or directory", "Error", "fail"...

**Comment by ivan-hc** [comment]
I think that the issue is mainly in the AppRun at
```
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"
```
the AppImage relies on some system libraries, for example `libpango`

**Comment by KevinFan9729** [comment]
Hmm...

I tested the Debian appimage on a fedora vm and it launches.
However, 1: it wants to create a new keyring. 2, some ui elements are not properly rendered (the minimise, maximise, close buttons are greyed out) 
![Screenshot from 2024-06-27 12-04-26](https://github.com/ivan-hc/Chromium-Web-Browser-appimage/assets/60720175/5f34f61f-c928-446a-837d-df99f3faca9f)

**Comment by ivan-hc** [comment]
> 1: it wants to create a new keyring.

I think this is because this is a complete different base, the previous one was a Chromium browser runnung into an Arch Linux container managed by bubblewrap, all bundled into an AppImage. This one instead is 100% Debian packages. A classic AppImage construction. So profiles may be different

> 2, some ui elements are not properly rendered (the minimise, maximise, close buttons are greyed out)

by default, Chromium should have its UI, you may change it in the settings to force GTK

**Comment by ivan-hc** [comment]
> I tested the Debian appimage on a fedora vm and it launches. So I think you are right that some system packages not used which is not available on my ubuntu host. Looking at the error `undefined symbol: hb_set_copy `, it seems that [harfbuzz](https://harfbuzz.github.io/harfbuzz-hb-set.html#) is the package that is in question? Should this package or can this package be included so the appimage is more platform independent?

Maybe. Note that this AppImage also relies on system packages.  This is the AppRun
```
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${PATH}"
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${HERE}"/usr/lib/python*/:"${PYTHONPATH}"
export PYTHONHOME="${HERE}"/usr/:"${HERE}"/usr/lib/python*/
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
exec ${HERE}/usr/lib/chromium/chromium "$@"
```
see
```
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"
```
the part
```
/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:
```
relies on system libraries

**Comment by KevinFan9729** [comment]
yeah I can see that

**Comment by ivan-hc** [comment]
@KevinFan9729 can you run the AppImage with LD_BEBUG=libs ? Like this
```
LD_DEBUG=libs ./*.AppImage
```
so I can see if there is a missing library I can include.

**Comment by ivan-hc** [comment]
Also, what package provides harfbuzz?

**Comment by KevinFan9729** [comment]
> @KevinFan9729 can you run the AppImage with LD_BEBUG=libs ? Like this
> 
> ```
> LD_DEBUG=libs ./*.AppImage
> ```
> 
> so I can see if there is a missing library I can include.

here
[log.txt](https://github.com/user-attachments/files/16019364/log.txt)

**Comment by KevinFan9729** [comment]
> Also, what package provides harfbuzz?

Not too sure, on fedora, [harfbuzz](https://packages.fedoraproject.org/pkgs/harfbuzz/) is a package.

**Comment by ivan-hc** [comment]
I can see that it is already included in the package
![Istantanea_2024-06-27_20-48-00 png](https://github.com/ivan-hc/Chromium-Web-Browser-appimage/assets/88724353/260cbebd-3393-4108-a655-2a702a2f6803)

maybe the error is due to differences between the AppImage's internal libraries and the guest (Fedora).

About custom URLs of this issue, is this package what you were looking for?

**Comment by KevinFan9729** [comment]
Ah no, this is not related to the custom url issue I raised originally. We kinda sidetracked to this issue as the Debian appimage is not launchable on my Ubuntu machine and it's having some issues with the fedora. What system libraries are critical for this appimage? Do you think it's a good idea to make it as self-sufficient as possible so it can be truly cross-distro?

I will also test out the MIME type handle in the current Debain appimage though.

**Comment by ivan-hc** [comment]
A big issue I have with many Debian-based AppImages I have is that they rely on libpango, that depends on glibc, that are not included with pkg2appimage not to create a bloated packages (as the Arch Linux-based is) nor to conflict ldd with two different glibc (I guess).

**Comment by ivan-hc** [comment]
@KevinFan9729 just uploaded a version of Chromium built from a very new base that I've tested only with Skype and now this: the Snap package.

Try this new release and tell me if everything works as it should. No system libraries required here

https://github.com/ivan-hc/Chromium-Web-Browser-appimage/releases/tag/continuous

**Comment by KevinFan9729** [comment]
Interesting, extracting a snap package and package it into an appimage...
It is launchable on my ubuntu host.
On Fedora, it still wants a keyring but it launches. 
I will test the MIME type with this appimage.

btw, it needs `libbsd` to be launchable.

**Comment by ivan-hc** [comment]
I close this issue for inactivity
