### ISSUE TITLE
errors running on "debian-11.10.0", version X11, --no wayland--

### ISSUE THREAD

**Issue by mladinox** [ivan-hc/Chromium-Web-Browser-appimage#8]
first off: great job, keep going,..
running the "chromium-browsers---.Appimages, on debian 11-10, throws several erros like below:
command: 
--> ./Chromium-stable-128.0.6613.119-x86_64.AppImage 
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/libffmpeg.so)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/libffmpeg.so)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/x86_64-linux-gnu/libnssutil3.so)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/x86_64-linux-gnu/libnspr4.so)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/x86_64-linux-gnu/libnspr4.so)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/x86_64-linux-gnu/libX11.so.6)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/x86_64-linux-gnu/libX11.so.6)
/tmp/.mount_ChromiPEdHaF/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiPEdHaF/usr/lib/x86_64-linux-gnu/libXau.so.6)
command:
--> ./Chromium-candidate-128.0.6613.137-x86_64.AppImage 
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/libffmpeg.so)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/libffmpeg.so)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/x86_64-linux-gnu/libnssutil3.so)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/x86_64-linux-gnu/libnspr4.so)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/x86_64-linux-gnu/libnspr4.so)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/x86_64-linux-gnu/libX11.so.6)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/x86_64-linux-gnu/libX11.so.6)
/tmp/.mount_ChromiCJGoOp/usr/lib/chromium-browser/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ChromiCJGoOp/usr/lib/x86_64-linux-gnu/libXau.so.6)

**Comment by ivan-hc** [comment]
hi, Debian 11 has GLIBC 2.31, so it is older than the ones supported, so Ubuntu 22.04 and newer distros can use these AppImages.

https://repology.org/project/glibc/versions

All four AppImages are built on top of the Snap package, and it seems that the packages were built to work on systems with GLIBC 2.35 or newer.

Debian 12 has GLIBC 2.36 and Debian 13 (Testing) has GLIBC 2.40, on them the AppImages work without problems.

So the issue is related to the too old GLIBC version you have.

PS: previously, my AppImage was based on the Debian 11 package from the "security" repository, which they stopped updating. I had to change bases to have more and more up-to-date packages (before changing, I noticed that Chromium Stable from Debian 11 was 10 versions behind the upstream one). Also take a look at the .deb versions from the Debian repository to understand how much the Debian team care about Chromium for Debian Oldstable and Oldoldstable

https://packages.debian.org/search?keywords=chromium

I preferred to use Snap as a base because if I had used Debian 12 "Stable" the GLIBC version would not have been compatible with Ubuntu 22.04 LTS, as it is newer.

Greetings
